name: xllify build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: xllify Build
        uses: acornsoftuk/xllify-build@v1alpha2
        with:
          luau_files: |
            hello.luau
            demo_data.luau
          xllify_key: abcdefg-unused
