name: Demo XLL build

permissions:
  contents: write
  actions: read
  checks: write
  
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: xllify Build demo add-in
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: xllify Build
        id: xllify
        uses: acornsoftuk/xllify-build@v0.3.47-beta
        with:
          xll_filename: xllify_demo
          luau_scripts: |
            simple.luau
            black_scholes.luau
            trading.luau
            trading_demodata.luau
          xllify_key: not-needed

      # The .xll is now in your workspace at path in ${{ steps.xllify.outputs.xll_path }}
      # Do with it what you want. Sign it (recommended), upload it to a release, cloud storage
      # etc...

      - name: Upload XLL to workflow job
        uses: actions/upload-artifact@v4
        with:
          name: xllify_demo
          path: ${{ steps.xllify.outputs.xll_path }}

      - name: Upload XLL to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.xllify.outputs.xll_path }}
