name: Demo build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xllify Remote Build
        id: xllify
        uses: acornsoftuk/xllify-build@v0.1.0-alpha
        with:
          xll_filename: hello.xll
          luau_files: |
            hello.luau
            demo_data.luau

          xllify_key: ${{ secrets.XLLIFY_KEY }}

      # The .xll is now in your workspace!

      - name: Upload XLL to release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo "Uploading ${{ steps.xllify.outputs.xll_path }} to release $TAG_NAME..."
          gh release upload "$TAG_NAME" "${{ steps.xllify.outputs.xll_path }}" --clobber
          echo "Successfully uploaded XLL to release $TAG_NAME"
        env:
          GH_TOKEN: ${{ github.token }}
