name: Demo XLL build

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  build:
    name: xllify Demo add-in
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xllify Remote Build
        id: xllify
        uses: acornsoftuk/xllify-build@v0.2.2-beta
        with:
          xll_filename: xllify_demo.xll
          luau_files: |
            simple.luau
            black_scholes.luau
          xllify_key: ${{ secrets.XLLIFY_KEY }}

      # The .xll is now in your workspace. It is common to upload it as a release.

      - name: Upload XLL to release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo "Uploading ${{ steps.xllify.outputs.xll_path }} to release $TAG_NAME..."
          gh release upload "$TAG_NAME" "${{ steps.xllify.outputs.xll_path }}" --clobber
          echo "Successfully uploaded XLL to release $TAG_NAME"
        env:
          GH_TOKEN: ${{ github.token }}
